### ISSUE TITLE
Failed to build 

### ISSUE THREAD

**Issue by coreybruce** [AxioDL/metaforce#442] opened 2022-01-23 15:45 UTC
Hey just wanted to report a issue building it from source, here is my log

```
[1599/1714] Building CXX object Runtime/CMakeFiles/RuntimeCommonB.dir/World/CScriptStreamedMusic.cpp.o
FAILED: Runtime/CMakeFiles/RuntimeCommonB.dir/World/CScriptStreamedMusic.cpp.o 
/usr/bin/c++ -DBOO_HAS_GL=1 -DBOO_HAS_VULKAN=1 -DFMT_ARM_ABI_COMPATIBILITY=1 -DFMT_ENFORCE_COMPILE_STRING=1 -DFMT_EXCEPTIONS=0 -DGLEW_NO_GLU=1 -DIMGUI_USER_CONFIG=\"imconfig_user.h\" -DSENTRY_ENABLED=0 -DURDE_ZIP_INPUT_STREAM=1 -DUSE_OPTICK=0 -DVK_USE_PLATFORM_XCB_KHR=1 -DZE_ATHENA_TYPES=1 -I/mnt/Storage/Project/metaforce/out/hecl -I/mnt/Storage/Project/metaforce/Runtime -I/mnt/Storage/Project/metaforce/out/Runtime -I/mnt/Storage/Project/metaforce/extern/zeus/include -I/mnt/Storage/Project/metaforce/extern/athena/include -I/mnt/Storage/Project/metaforce/extern/athena/extern/fmt/include -I/mnt/Storage/Project/metaforce/hecl/lib/../include -I/mnt/Storage/Project/metaforce -I/mnt/Storage/Project/metaforce/DataSpec -I/mnt/Storage/Project/metaforce/extern/amuse/include -I/mnt/Storage/Project/metaforce/extern/athena/extern/lzokay -I/mnt/Storage/Project/metaforce/extern/nod/logvisor/include -I/mnt/Storage/Project/metaforce/extern/boo/include -I/mnt/Storage/Project/metaforce/extern/boo/include/boo/graphicsdev -I/mnt/Storage/Project/metaforce/extern/boo/glslang/glslang/.. -I/mnt/Storage/Project/metaforce/extern/boo/glslang/StandAlone -I/mnt/Storage/Project/metaforce/extern/boo -I/mnt/Storage/Project/metaforce/extern/boo/glslang -I/mnt/Storage/Project/metaforce/extern/boo/glslang/SPIRV/.. -I/mnt/Storage/Project/metaforce/extern/boo/optick/src -I/mnt/Storage/Project/metaforce/extern/nod/lib/../include -I/mnt/Storage/Project/metaforce/extern/libSquish -I/mnt/Storage/Project/metaforce/NESEmulator -I/mnt/Storage/Project/metaforce/extern/libjpeg-turbo -I/mnt/Storage/Project/metaforce/extern/jbus/include -I/mnt/Storage/Project/metaforce/extern/kabufuda/include -I/mnt/Storage/Project/metaforce/extern/discord-rpc/include -I/mnt/Storage/Project/metaforce/extern/imgui -I/mnt/Storage/Project/metaforce/imgui -O2 -g -DNDEBUG -msse4.1 -fno-plt -fno-rtti -fno-exceptions -Wall -Wno-multichar -Werror=implicit-fallthrough -Wno-unused-variable -Wno-unused-result -Wno-unused-but-set-variable -Wno-unused-function -Wno-sign-compare -Wno-unknown-pragmas -Werror -Wno-lto-type-mismatch -Wno-maybe-uninitialized -pthread -std=gnu++20 -MD -MT Runtime/CMakeFiles/RuntimeCommonB.dir/World/CScriptStreamedMusic.cpp.o -MF Runtime/CMakeFiles/RuntimeCommonB.dir/World/CScriptStreamedMusic.cpp.o.d -o Runtime/CMakeFiles/RuntimeCommonB.dir/World/CScriptStreamedMusic.cpp.o -c /mnt/Storage/Project/metaforce/Runtime/World/CScriptStreamedMusic.cpp
In file included from /mnt/Storage/Project/metaforce/hecl/lib/../include/hecl/Blender/Connection.hpp:37,
                 from /mnt/Storage/Project/metaforce/DataSpec/DNACommon/CMDL.hpp:12,
                 from /mnt/Storage/Project/metaforce/DataSpec/DNAMP1/CMDLMaterials.hpp:5,
                 from /mnt/Storage/Project/metaforce/Runtime/Graphics/Shaders/CModelShaders.hpp:7,
                 from /mnt/Storage/Project/metaforce/Runtime/Graphics/CMetroidModelInstance.hpp:9,
                 from /mnt/Storage/Project/metaforce/Runtime/World/CGameArea.hpp:10,
                 from /mnt/Storage/Project/metaforce/Runtime/Camera/CCameraManager.hpp:8,
                 from /mnt/Storage/Project/metaforce/Runtime/CStateManager.hpp:18,
                 from /mnt/Storage/Project/metaforce/Runtime/World/CScriptStreamedMusic.cpp:4:
/mnt/Storage/Project/metaforce/extern/athena/extern/fmt/include/fmt/ostream.h:123:8: error: partial specialization of ‘struct fmt::v7::detail::fallback_formatter<T, Char, typename std::enable_if<fmt::v7::detail::is_streamable<T, Char>::value, void>::type>’ after instantiation of ‘struct fmt::v7::detail::fallback_formatter<std::basic_string_view<char>, char, void>’ [-fpermissive]
  123 | struct fallback_formatter<T, Char, enable_if_t<is_streamable<T, Char>::value>>
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[1602/1714] Building CXX object Runtime/CMakeFiles/RuntimeCommonB.dir/World/CScriptMidi.cpp.o
FAILED: Runtime/CMakeFiles/RuntimeCommonB.dir/World/CScriptMidi.cpp.o 
/usr/bin/c++ -DBOO_HAS_GL=1 -DBOO_HAS_VULKAN=1 -DFMT_ARM_ABI_COMPATIBILITY=1 -DFMT_ENFORCE_COMPILE_STRING=1 -DFMT_EXCEPTIONS=0 -DGLEW_NO_GLU=1 -DIMGUI_USER_CONFIG=\"imconfig_user.h\" -DSENTRY_ENABLED=0 -DURDE_ZIP_INPUT_STREAM=1 -DUSE_OPTICK=0 -DVK_USE_PLATFORM_XCB_KHR=1 -DZE_ATHENA_TYPES=1 -I/mnt/Storage/Project/metaforce/out/hecl -I/mnt/Storage/Project/metaforce/Runtime -I/mnt/Storage/Project/metaforce/out/Runtime -I/mnt/Storage/Project/metaforce/extern/zeus/include -I/mnt/Storage/Project/metaforce/extern/athena/include -I/mnt/Storage/Project/metaforce/extern/athena/extern/fmt/include -I/mnt/Storage/Project/metaforce/hecl/lib/../include -I/mnt/Storage/Project/metaforce -I/mnt/Storage/Project/metaforce/DataSpec -I/mnt/Storage/Project/metaforce/extern/amuse/include -I/mnt/Storage/Project/metaforce/extern/athena/extern/lzokay -I/mnt/Storage/Project/metaforce/extern/nod/logvisor/include -I/mnt/Storage/Project/metaforce/extern/boo/include -I/mnt/Storage/Project/metaforce/extern/boo/include/boo/graphicsdev -I/mnt/Storage/Project/metaforce/extern/boo/glslang/glslang/.. -I/mnt/Storage/Project/metaforce/extern/boo/glslang/StandAlone -I/mnt/Storage/Project/metaforce/extern/boo -I/mnt/Storage/Project/metaforce/extern/boo/glslang -I/mnt/Storage/Project/metaforce/extern/boo/glslang/SPIRV/.. -I/mnt/Storage/Project/metaforce/extern/boo/optick/src -I/mnt/Storage/Project/metaforce/extern/nod/lib/../include -I/mnt/Storage/Project/metaforce/extern/libSquish -I/mnt/Storage/Project/metaforce/NESEmulator -I/mnt/Storage/Project/metaforce/extern/libjpeg-turbo -I/mnt/Storage/Project/metaforce/extern/jbus/include -I/mnt/Storage/Project/metaforce/extern/kabufuda/include -I/mnt/Storage/Project/metaforce/extern/discord-rpc/include -I/mnt/Storage/Project/metaforce/extern/imgui -I/mnt/Storage/Project/metaforce/imgui -O2 -g -DNDEBUG -msse4.1 -fno-plt -fno-rtti -fno-exceptions -Wall -Wno-multichar -Werror=implicit-fallthrough -Wno-unused-variable -Wno-unused-result -Wno-unused-but-set-variable -Wno-unused-function -Wno-sign-compare -Wno-unknown-pragmas -Werror -Wno-lto-type-mismatch -Wno-maybe-uninitialized -pthread -std=gnu++20 -MD -MT Runtime/CMakeFiles/RuntimeCommonB.dir/World/CScriptMidi.cpp.o -MF Runtime/CMakeFiles/RuntimeCommonB.dir/World/CScriptMidi.cpp.o.d -o Runtime/CMakeFiles/RuntimeCommonB.dir/World/CScriptMidi.cpp.o -c /mnt/Storage/Project/metaforce/Runtime/World/CScriptMidi.cpp
In file included from /mnt/Storage/Project/metaforce/hecl/lib/../include/hecl/Blender/Connection.hpp:37,
                 from /mnt/Storage/Project/metaforce/DataSpec/DNACommon/CMDL.hpp:12,
                 from /mnt/Storage/Project/metaforce/DataSpec/DNAMP1/CMDLMaterials.hpp:5,
                 from /mnt/Storage/Project/metaforce/Runtime/Graphics/Shaders/CModelShaders.hpp:7,
                 from /mnt/Storage/Project/metaforce/Runtime/Graphics/CMetroidModelInstance.hpp:9,
                 from /mnt/Storage/Project/metaforce/Runtime/World/CGameArea.hpp:10,
                 from /mnt/Storage/Project/metaforce/Runtime/Camera/CCameraManager.hpp:8,
                 from /mnt/Storage/Project/metaforce/Runtime/CStateManager.hpp:18,
                 from /mnt/Storage/Project/metaforce/Runtime/World/CScriptMidi.cpp:5:
/mnt/Storage/Project/metaforce/extern/athena/extern/fmt/include/fmt/ostream.h:123:8: error: partial specialization of ‘struct fmt::v7::detail::fallback_formatter<T, Char, typename std::enable_if<fmt::v7::detail::is_streamable<T, Char>::value, void>::type>’ after instantiation of ‘struct fmt::v7::detail::fallback_formatter<std::basic_string_view<char>, char, void>’ [-fpermissive]
  123 | struct fallback_formatter<T, Char, enable_if_t<is_streamable<T, Char>::value>>
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[1606/1714] Building CXX object Runtime/CMakeFiles/RuntimeCommonB.dir/World/CTeamAiMgr.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by Antidote** [comment] 2022-01-23 17:20
Duplicate of #439

**Closed by Antidote** 2022-01-23 17:20 UTC
