### ISSUE TITLE
Issues building urde

### ISSUE THREAD

**Issue by TheBillzar1640** [AxioDL/metaforce#367] opened 2021-02-07 05:53 UTC
I have all the prerequisites installed and using Visual Studio 2019 on Windows 10.

When opening the folder in Visual Studio it begins to build as usual, then stops after a few seconds with 7 errors and 1 warning:

1. CMake Error at Shaders/CMakeLists.txt:12 (add_shader):
  Unknown CMake command "add_shader".		E:\Downloads\URDE\urde\Shaders/CMakeLists.txt	12	

2. CMake Error at E:\Downloads\URDE\urde\CMakeLists.txt:266 (add_subdirectory):
  add_subdirectory given source "discord-rpc/src" which is not an existing
  directory.	urde	E:\Downloads\URDE\urde\CMakeLists.txt	266	

3. CMake Error at E:\Downloads\URDE\urde\CMakeLists.txt:267 (target_include_directories):
  Cannot specify include directories for target "discord-rpc" which is not
  built by this project.	urde	E:\Downloads\URDE\urde\CMakeLists.txt	267	

4. CMake Error at E:\Downloads\URDE\urde\CMakeLists.txt:270 (add_subdirectory):
  The source directory
  E:/Downloads/URDE/urde/nod
  does not contain a CMakeLists.txt file.	urde	E:\Downloads\URDE\urde\CMakeLists.txt	270	

5. CMake Error at E:\Downloads\URDE\urde\CMakeLists.txt:302 (add_subdirectory):
  add_subdirectory given source "hecl/shaderc" which is not an existing
  directory.	urde	E:\Downloads\URDE\urde\CMakeLists.txt	302	

6. CMake Error at E:\Downloads\URDE\urde\CMakeLists.txt:303 (include):
  include could not find load file:
    hecl/ApplicationTools.cmake	urde	E:\Downloads\URDE\urde\CMakeLists.txt	303	

7. CMake Error at E:\Downloads\URDE\urde\CMakeLists.txt:304 (add_subdirectory):
  add_subdirectory given source "specter/shaders" which is not an existing
  directory.	urde	E:\Downloads\URDE\urde\CMakeLists.txt	304	

1. CMake Warning at E:\Downloads\URDE\urde\CMakeLists.txt:55 (find_package):
  By not providing "FindSanitizers.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Sanitizers", but CMake did not find one.

  Could not find a package configuration file provided by "Sanitizers" with
  any of the following names:

    SanitizersConfig.cmake
    sanitizers-config.cmake

  Add the installation prefix of "Sanitizers" to CMAKE_PREFIX_PATH or set
  "Sanitizers_DIR" to a directory containing one of the above files.  If
  "Sanitizers" provides a separate development package or SDK, be sure it has
  been installed.	urde	E:\Downloads\URDE\urde\CMakeLists.txt	55	

Sorry if I'm being dumb and missing something obvious and that this isn't something directly involving the urde in-game, I want to get to that stage to help find issues but am struggling with this - any help is appreciated, thank you very much in advance!

**Comment by Antidote** [comment] 2021-02-07 06:00
Did you run `git submodule update --init --recursive`? this looks like an incomplete clone.

**Comment by TheBillzar1640** [comment] 2021-02-07 06:21
Just doing this now, I will update once it's finished

**Comment by TheBillzar1640** [comment] 2021-02-07 06:41
No more errors but 1 warning - which is amazing compared to what I had before, thank you very much!

The warning is:

1. CMake Warning at hecl/extern/boo/CMakeLists.txt:87 (message):
  IPP not found; skipping support	boo	E:\Downloads\URDE\urde\hecl/extern/boo/CMakeLists.txt	87	

The build appears to have finished, with the output window ending with "CMake generation finished."

The only other issue I've had is that I've used the latest dev release of urde (24th Aug 2020) to try and run the packaged file (prime/out for me) but it kept closing a few seconds after dragging the file over urde.exe or using the command "urde prime\out" - which is why I wanted to clone the latest repository files so I'm as up-to-date as I can be. How would I go about using what I've built to run the file (as the urde.exe is not present as a standalone executable)? 

Also the log I got from trying to run the packaged file earlier is included to show how far it got before closing. Again, thank you very much!
![error](https://user-images.githubusercontent.com/65400694/107138925-7dbe9500-690f-11eb-944d-95bdff289fc8.png)

**Comment by TheBillzar1640** [comment] 2021-02-07 13:24
Ok I've searched around the built folder and have not found any executables for urde, hecl or visigen. After looking at the output window in Visual Studio I've noticed an oddity:

1> CMake generation started for configuration: 'x64-Clang-Release'.
1> Environment settings:
1>     CXXFLAGS=-m64 -fdiagnostics-absolute-paths
1>     CFLAGS=-m64 -fdiagnostics-absolute-paths
1> Command line: "cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "E:\VISUAL STUDIO\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo" -DCMAKE_INSTALL_PREFIX:PATH="E:\Downloads\URDE\urde\out\install\x64-Clang-Release" -DCMAKE_MSVC_RUNTIME_LIBRARY:STRING="MultiThreaded" -DCMAKE_C_COMPILER:FILEPATH="C:\Program Files\LLVM\bin\clang-cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:\Program Files\LLVM\bin\clang-cl.exe" -DCMAKE_LINKER:FILEPATH="C:\Program Files\LLVM\bin\lld-link.exe" -DCMAKE_AR:FILEPATH="C:\Program Files\LLVM\bin\llvm-ar.exe" -DCMAKE_RANLIB:FILEPATH="C:\Program Files\LLVM\bin\llvm-ranlib.exe"  -DCMAKE_MAKE_PROGRAM="E:\VISUAL STUDIO\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "E:\Downloads\URDE\urde" 2>&1"
1> Working directory: E:\Downloads\URDE\urde\out\build\x64-Clang-Release
1> [CMake] -- Building with SSE2 Vector ISA
1> [CMake] -- Version: 6.2.0
1> [CMake] -- Build type: RelWithDebInfo
1> [CMake] -- CXX_STANDARD: 11
1> [CMake] -- Required features: cxx_variadic_templates
1> [CMake] -- Could NOT find IPP (missing: IPP_INCLUDE_DIR IPP_LIBRARY) 
1> [CMake] CMake Warning at hecl/extern/boo/CMakeLists.txt:87 (message):
1> [CMake]   IPP not found; skipping support
1> [CMake] 
1> [CMake] 
1> [CMake] -- Using Athena's built-in zlib
1> [CMake] -- Using HECL's built-in libpng
1> [CMake] -- Could NOT find Qt6 (missing: Qt6_DIR)
1> [CMake] -- Qt6 not found, amuse-gui will not be built
1> [CMake] -- Creating directory E:/Downloads/URDE/urde/out/build/x64-Clang-Release/specter/freetype2/include/freetype/config
1> [CMake] -- Creating file E:/Downloads/URDE/urde/out/build/x64-Clang-Release/specter/freetype2/include/freetype/config/ftconfig.h
1> [CMake] -- Could NOT find Qt6Widgets (missing: Qt6Widgets_DIR)
1> [CMake] -- Qt6 not found, hecl-gui will not be built
1> [CMake] -- Configuring done
1> [CMake] -- Generating done
1> [CMake] -- Build files have been written to: E:/Downloads/URDE/urde/out/build/x64-Clang-Release
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted code model.
1> Extracted includes paths.
1> CMake generation finished.

Qt6 not being found is preventing hecl-gui from being built, which I've read is a folder that contains what's required to run Prime. What should I do from here? I apologize for causing any trouble or keeping developers away from the game, thank you in advance!

**Comment by tomlube** [comment] 2021-02-07 14:03
> Ok I've searched around the built folder and have not found any executables for urde, hecl or visigen. After looking at the output window in Visual Studio I've noticed an oddity:
> 
> 1> CMake generation started for configuration: 'x64-Clang-Release'.
> 1> Environment settings:
> 1> CXXFLAGS=-m64 -fdiagnostics-absolute-paths
> 1> CFLAGS=-m64 -fdiagnostics-absolute-paths
> 1> Command line: "cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "E:\VISUAL STUDIO\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe" -G "Ninja" -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo" -DCMAKE_INSTALL_PREFIX:PATH="E:\Downloads\URDE\urde\out\install\x64-Clang-Release" -DCMAKE_MSVC_RUNTIME_LIBRARY:STRING="MultiThreaded" -DCMAKE_C_COMPILER:FILEPATH="C:\Program Files\LLVM\bin\clang-cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:\Program Files\LLVM\bin\clang-cl.exe" -DCMAKE_LINKER:FILEPATH="C:\Program Files\LLVM\bin\lld-link.exe" -DCMAKE_AR:FILEPATH="C:\Program Files\LLVM\bin\llvm-ar.exe" -DCMAKE_RANLIB:FILEPATH="C:\Program Files\LLVM\bin\llvm-ranlib.exe" -DCMAKE_MAKE_PROGRAM="E:\VISUAL STUDIO\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "E:\Downloads\URDE\urde" 2>&1"
> 1> Working directory: E:\Downloads\URDE\urde\out\build\x64-Clang-Release
> 1> [CMake] -- Building with SSE2 Vector ISA
> 1> [CMake] -- Version: 6.2.0
> 1> [CMake] -- Build type: RelWithDebInfo
> 1> [CMake] -- CXX_STANDARD: 11
> 1> [CMake] -- Required features: cxx_variadic_templates
> 1> [CMake] -- Could NOT find IPP (missing: IPP_INCLUDE_DIR IPP_LIBRARY)
> 1> [CMake] CMake Warning at hecl/extern/boo/CMakeLists.txt:87 (message):
> 1> [CMake] IPP not found; skipping support
> 1> [CMake]
> 1> [CMake]
> 1> [CMake] -- Using Athena's built-in zlib
> 1> [CMake] -- Using HECL's built-in libpng
> 1> [CMake] -- Could NOT find Qt6 (missing: Qt6_DIR)
> 1> [CMake] -- Qt6 not found, amuse-gui will not be built
> 1> [CMake] -- Creating directory E:/Downloads/URDE/urde/out/build/x64-Clang-Release/specter/freetype2/include/freetype/config
> 1> [CMake] -- Creating file E:/Downloads/URDE/urde/out/build/x64-Clang-Release/specter/freetype2/include/freetype/config/ftconfig.h
> 1> [CMake] -- Could NOT find Qt6Widgets (missing: Qt6Widgets_DIR)
> 1> [CMake] -- Qt6 not found, hecl-gui will not be built
> 1> [CMake] -- Configuring done
> 1> [CMake] -- Generating done
> 1> [CMake] -- Build files have been written to: E:/Downloads/URDE/urde/out/build/x64-Clang-Release
> 1> Extracted CMake variables.
> 1> Extracted source files and headers.
> 1> Extracted code model.
> 1> Extracted includes paths.
> 1> CMake generation finished.
> 
> Qt6 not being found is preventing hecl-gui from being built, which I've read is a folder that contains what's required to run Prime. What should I do from here? I apologize for causing any trouble or keeping developers away from the game, thank you in advance!

HECL GUI is not required to build URDE/extract/repackage, in fact I don't believe it's even functional at this moment. Where are you searching for executables?

**Comment by TheBillzar1640** [comment] 2021-02-07 23:16
Sorry for getting back so late, I've checked the folder and it appears to be empty (both the Clang-Debug and Clang-Release builds).

**Comment by TheBillzar1640** [comment] 2021-02-08 03:13
Upon using Visual Studio to rebuild the project from scratch, an option called "Install urde" appears under the build drop-down menu. When pressing this - the build proceeds to go until this line:

```
[69/1850] C:\PROGRA~1\LLVM\bin\clang-cl.exe  /nologo -TP -DD_SCL_SECURE_NO_WARNINGS=1 -DENABLE_OPT=0 -DFMT_EXCEPTIONS=0 -DNOMINMAX=1 -DUNICODE=1 -D_CRT_NONSTDC_NO_WARNINGS=1 -D_CRT_SECURE_NO_WARNINGS=1 -D_ENABLE_EXTENDED_ALIGNED_STORAGE=1 -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_DEPRECATE=1 -D_UNICODE=1 -D__SSE__=1 -Ihecl -I..\..\..\hecl\extern\boo\glslang\glslang\.. -m64 -fdiagnostics-absolute-paths  /DWIN32 /D_WINDOWS /GR /EHsc /Zi /O2 /Ob1 /DNDEBUG -MT /IGNORE:4221 /wd4018 /wd4800 /wd4005 /wd4311 /wd4068 /wd4267 /wd4244 /wd4200 /wd4305 /wd4067 /wd4146 /wd4309 /wd4805 /EHsc- /GR- /permissive- /volatile:iso /Zc:__cplusplus /std:c++latest /showIncludes /Fohecl\extern\boo\glslang\glslang\CMakeFiles\glslang.dir\MachineIndependent\glslang_tab.cpp.obj /Fdhecl\extern\boo\glslang\glslang\CMakeFiles\glslang.dir\glslang.pdb -c ..\..\..\hecl\extern\boo\glslang\glslang\MachineIndependent\glslang_tab.cpp
  ninja: build stopped: subcommand failed.
Install succeeded.
```

There are 2 errors which are both "unknown option /" and point to the root CMakeLists.txt project with the file being llvm-ar.exe on line 1:

`unknown option /	E:\Downloads\URDE\urde\CMakeLists.txt	C:\Program Files\LLVM\bin\llvm-ar.exe	1	`


There were also 3 warnings as well, the one from earlier about "IPP not found, skipping support" and the other two pointing to the same CMakeLists.txt project from before but they each point to a different file:
1. `pragma STDC FENV_ACCESS ON is not supported, ignoring pragma [-Wunknown-pragmas]	E:\Downloads\URDE\urde\CMakeLists.txt	E:\Downloads\URDE\urde\hecl\extern\boo\soxr\src\data-io.c	96`

2. `arithmetic between enumeration type 'DEVICE_SCALE_FACTOR' and floating-point type 'float' is deprecated [-Wdeprecated-enum-float-conversion]
E:\Downloads\URDE\urde\CMakeLists.txt	E:\Downloads\URDE\urde\hecl\extern\boo\lib\win\WindowWin32.cpp	988`

**Comment by Antidote** [comment] 2021-02-08 05:14
That llvm-ar error is known, and unfortunately we can't fix that, it's a regression with VS' cmake integration.

**Comment by TheBillzar1640** [comment] 2021-02-08 09:02
Ah, ok. Thank you for clearing that up - is there anything I can do to proceed past this point or is it best to use a build from the releases for now?
Thank you again for helping out!

**Comment by encounter** [comment] 2021-02-16 02:59
b171f34b123cbfd3e56ceac00771106f8e878c13 fixes the llvm-ar issue when compiling with clang-cl. 

MSVC compilation was also fixed with 5f263b8a4fb9d147fe6665c8914292c2157ffbf3.

**Comment by TheBillzar1640** [comment] 2021-02-16 11:03
The project (built using x64-Clang-Debug) has built successfully and I now have all the binary files! Thank you very much!

The only issue now is that when using cmd to perform the "urde prime/out" command or dragging the out file from prime onto the urde executable to load the game up (extracted from the iso and repackaged using hecl) it loads urde up for around 3 seconds and then closes. 

This is as far as it gets before closing:
![urdeclose](https://user-images.githubusercontent.com/65400694/108054404-8406ec80-7046-11eb-9ce5-032c36fa5c69.png)

**Comment by encounter** [comment] 2021-02-16 17:11
Try running with logging enabled: `.\urde.exe -l prime/out` which hopefully will give more information.

**Comment by TheBillzar1640** [comment] 2021-02-16 17:25
Here's the log:
![urdecloselog](https://user-images.githubusercontent.com/65400694/108098966-e9c19b80-707b-11eb-81dc-85d8f82096a7.png)

**Comment by encounter** [comment] 2021-02-16 17:29
It looks like you may not have built URDE with Vulkan support, try `--vulkan` and see if it still tries D3D11.

After installing the Vulkan SDK, re-run cmake and make sure `Enabling Vulkan support` shows up in the logs.

This may be unrelated to the crash, but it's the most supported graphics backend.

**Comment by TheBillzar1640** [comment] 2021-02-16 18:33
I've installed the Vulkan SDK and re-built the program in both x64-Clang-Debug and Release (both saying that Vulkan support is enabled) using both the method of dragging the out folder over the urde executable and running the command line `urde.exe -l prime/out` with the `--vulkan` extension at the end with similar results:
![urdecloselog2](https://user-images.githubusercontent.com/65400694/108106034-55f4cd00-7085-11eb-8534-bb697724d716.png)

**Comment by TheBillzar1640** [comment] 2021-02-26 06:53
I've just extracted my prime.iso with the latest build of hecl (Clang-release) and got as far as the urde stage again (where it won't start prime up in game mode) but I've ended up with a different result then last time:

![urdestaylog](https://user-images.githubusercontent.com/65400694/109263535-5581d200-77fb-11eb-8d9c-460fd6a658a0.png)

Urde is not closing this time, but is instead stuck on this screen with the log going as far as this (it was stuck like this for around 30 minutes without any progress) the only thing I've done differently besides re-extracting the .iso is using urde from Clang-debug instead of Clang-release (because it keeps closing like last time when using release). The other thing I've noticed is that when extracting the game using the latest hecl (again in Clang-release) it stops at this point in the extraction process: 

![errorhecl](https://user-images.githubusercontent.com/65400694/109264867-895df700-77fd-11eb-82ef-8a8fada985e8.png)

This might be what is causing urde to not open the packaged files correctly?

One final thing to mention is that I tried to extract the .iso using the Clang-debug build of the commit and it ended up with a fairly large error: 

![errorcmd](https://user-images.githubusercontent.com/65400694/109265129-f5d8f600-77fd-11eb-8785-33064cbcd4e2.png)
![errorcmd2](https://user-images.githubusercontent.com/65400694/109265198-1012d400-77fe-11eb-99ab-0911852c2995.png)

It throws up the "Debug Assertion Failed!" message after a little while after starting the extract and continues in the background for a short while longer until it eventually gives me the "Debug Error!" message (despite the fact that I did not debug the previous error, I simply left it up thinking that it was only minor as the extraction process had not stopped in the background) and fills the command prompt with the FATAL ERROR shown above.

Thank you for your help so far! I hope I'm not being an inconvenience to the project.

**Comment by TheBillzar1640** [comment] 2021-02-28 03:14
Alright, I've gotten it to work!

I've downloaded the latest successful dev build of URDE (February 21st 2021 at the time of this comment) and extracted and packaged the .iso in its entirety from start to finish with complete success! Thank you so much for your help during my, personally, silly start with trying to get Metroid Prime to run with URDE.

I have so far gotten to the start of the game and nothing has gone very wrong so I'm confident that everything should hopefully stay good on my end! While I'm testing out URDE I'll have the original .iso running with Dolphin to check for accuracies and I also have the original disk on GameCube as well (although it's the PAL version, I assume this is the NTSC version which I have for Dolphin) so I can help out a lot more thoroughly and actually contribute some assistance if needed.

Again, thank you for everything!

**Comment by tomlube** [comment] 2021-06-13 22:38
Fixed a long time ago actually

**Closed by tomlube** 2021-06-13 22:38 UTC
